// Crag database — Melbourne climber's regular destinations
// Each crag has lat/lon, aspect, elevation, dry-out time, and notes.
// Sub-areas where it matters (Arapiles, Grampians).
//
// Aspect codes: N, NE, E, SE, S, SW, W, NW
// dryRating: 1 (slow to dry, holds moisture) → 5 (very fast, dries in hours)
// idealTemp: [min, max] °C — sweet spot for friction & comfort
// shade: "morning", "afternoon", "all-day", "none" — when shade is available
// rockType: granite, sandstone, quartzite — used for context
// trip: "day" (<3h drive, day-trip from Melbourne) or "weekend" (3h+, overnight worth it)
// heatCap: (optional) temperature in °C above which the crag becomes uncomfortable on clear days (e.g. N-aspect sun-baths)

export const CRAGS = [
  // — Metro / day-trip —
  {
    id: 'camels-hump',
    name: "Camel's Hump",
    area: 'Mt Macedon',
    lat: -37.3947,
    lon: 144.5547,
    elevation: 950,
    aspect: 'W',
    rockType: 'trachyte',
    dryRating: 4,
    idealTemp: [10, 24],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'Ideal in summer — 950m elevation keeps it noticeably cooler than the city on a hot day. Lower Tier is north-facing but heavily tree-shaded. Omega Block (W/S-facing) catches afternoon and late-afternoon sun. Dries quickly after rain.',
    sunOnWall: 'Omega Block: sun from late afternoon; Lower Tier: shaded by forest',
    bestIn: 'mild',
  },
  {
    id: 'ben-cairn',
    name: 'Ben Cairn',
    area: 'Mt Macedon',
    lat: -37.4050,
    lon: 144.5650,
    elevation: 900,
    aspect: 'SE',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 26],
    shade: 'afternoon',
    driveTime: '1h',
    trip: 'day',
    notes: 'SE-facing granite at 900m near Mt Macedon. Morning sun then shade — generally shady character. Good summer option when lower crags are too hot.',
    sunOnWall: 'Morning sun; shaded from midday',
    bestIn: 'warm',
  },
  {
    id: 'falcons-lookout',
    name: 'Falcons Lookout',
    area: 'Werribee Gorge',
    lat: -37.6736,
    lon: 144.4322,
    elevation: 250,
    aspect: 'N',
    rockType: 'conglomerate',
    dryRating: 3,
    idealTemp: [8, 18],
    heatCap: 22,
    shade: 'none',
    driveTime: '50min',
    trip: 'day',
    notes: 'Ideal in winter. Veni Vedi Vici is N-facing, sun all day — a genuine sun trap. The Amphitheatre is E-facing, late-afternoon shade, also a sun trap. Conglomerate dries fast in sun and wind.',
    sunOnWall: 'Most of the day (north-facing)',
    bestIn: 'cool',
  },
  // — Cathedral Ranges sub-areas —
  {
    id: 'cathedral-main',
    name: 'Cathedral Ranges',
    area: 'Cathedral Ranges',
    lat: -37.3667,
    lon: 145.7333,
    elevation: 920,
    aspect: 'mixed',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'mixed',
    driveTime: '1h45',
    trip: 'both',
    notes: 'Sandstone ridge ~1h45 NE of Melbourne (Buxton/Taggerty). 900–950m elevation keeps it noticeably cooler than the valley. Mix of single-pitch sport and committing multi-pitch trad along an exposed spine. Check sub-crags for today’s aspect.',
    sunOnWall: 'Mixed — depends on sub-crag aspect',
    bestIn: 'mild',
  },
  {
    id: 'cathedral-balcony',
    parentId: 'cathedral-main',
    name: 'The Balcony',
    area: 'Cathedral Ranges',
    lat: -37.3667,
    lon: 145.7472,
    elevation: 940,
    aspect: 'SE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [10, 24],
    shade: 'afternoon',
    driveTime: '1h45',
    trip: 'both',
    notes: 'Exposed ridge-top crag with a mix of sport and trad. SE-facing — morning sun, shaded from midday. 940m elevation keeps temps below the valley. Dries fast in wind. Approach is committing.',
    sunOnWall: 'Morning sun; shaded from midday',
    bestIn: 'mild',
  },
  {
    id: 'cathedral-sugarloaf',
    parentId: 'cathedral-main',
    name: 'Sugarloaf Peak',
    area: 'Cathedral Ranges',
    lat: -37.3614,
    lon: 145.7458,
    elevation: 924,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 24],
    shade: 'afternoon',
    driveTime: '1h45',
    trip: 'both',
    notes: 'Dramatic exposed peak with multi-pitch trad on a south-east face — Northern Buttress Direct and Wells of Sadness are the classics. South-facing aspect stays shaded most of the day, making it one of the best hot-summer-day options near Melbourne. Committing position; weather rolls in fast. Slower to dry than The Balcony.',
    sunOnWall: 'Brief morning only (SE aspect)',
    bestIn: 'mild',
  },
  {
    id: 'cathedral-northjawbone',
    parentId: 'cathedral-main',
    name: 'North Jawbone',
    area: 'Cathedral Ranges',
    lat: -37.3530,
    lon: 145.7400,
    elevation: 880,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 24],
    shade: 'afternoon',
    driveTime: '1h45',
    trip: 'both',
    notes: 'East-facing — morning sun, afternoon shade. Steep committing multi-pitch trad.',
    sunOnWall: 'Morning sun; afternoon shade',
    bestIn: 'mild',
  },
  {
    id: 'cathedral-southjawbone',
    parentId: 'cathedral-main',
    name: 'South Jawbone',
    area: 'Cathedral Ranges',
    lat: -37.3570,
    lon: 145.7400,
    elevation: 875,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 24],
    shade: 'afternoon',
    driveTime: '1h45',
    trip: 'both',
    notes: 'East-facing — morning sun, afternoon shade. Multi-pitch trad on the south end of the Cathedral Ranges ridge.',
    sunOnWall: 'Morning sun; afternoon shade',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-main',
    name: 'You Yangs',
    area: 'You Yangs',
    lat: -37.9489,
    lon: 144.4297,
    elevation: 320,
    aspect: 'NW',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 20],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'Granite slabs and aretes. Big Rock Main Face is WNW — morning shade, afternoon roast. Dries within hours. Get there early in summer.',
    sunOnWall: 'Afternoon (morning shade)',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-flatrock',
    name: 'Flat Rock',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9531,
    lon: 144.4250,
    elevation: 280,
    aspect: 'SE',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [12, 22],
    shade: 'afternoon',
    driveTime: '1h',
    trip: 'day',
    notes: 'Bouldering-heavy area. Faster-drying than Main. SE aspect = cooler in afternoon.',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-gravelpit',
    name: 'Gravel Pit Tor',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9461,
    lon: 144.4262,
    elevation: 300,
    aspect: 'NW',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 20],
    shade: 'afternoon',
    driveTime: '1h',
    trip: 'day',
    notes: 'Stand-alone monolith with the steepest sport routes in the park — Edging Bets, A Question of Ethics, Silver Knight. SE-facing main wall: morning sun then shade by midday. Granite dries within hours.',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-royaltywalls',
    name: 'Royalty Walls',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9512,
    lon: 144.4231,
    elevation: 290,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [8, 20],
    shade: 'none',
    driveTime: '1h',
    trip: 'day',
    notes: 'Lesser-trafficked walls with a mix of slabs and short faces. West-facing — afternoon sun, cooler mornings. Good when Gravel Pit is busy or wet.',
    bestIn: 'cool',
  },
  {
    id: 'youyangs-adamblock',
    name: 'Adam Block',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9495,
    lon: 144.4283,
    elevation: 310,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [8, 18],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'Compact block in the Saddle Area. Home to the classic line Adam (26) — a left-trending crack capped by an offwidth through a roof. West aspect catches afternoon sun; best on cooler days when the crack is dry.',
    bestIn: 'cool',
  },
  {
    id: 'youyangs-urinalwall',
    name: 'Urinal Wall',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9480,
    lon: 144.4290,
    elevation: 305,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [8, 20],
    shade: 'none',
    driveTime: '1h',
    trip: 'day',
    notes: 'North/west-facing wall with all-day sun and light shade. Good cool-weather option.',
    sunOnWall: 'All day (light shade)',
    bestIn: 'cool',
  },
  {
    id: 'youyangs-flindersslabs',
    name: 'Flinders Peak Slabs',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9440,
    lon: 144.4310,
    elevation: 330,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '1h',
    trip: 'day',
    notes: 'East-facing slabs with no shade — full morning sun until midday. Best on cool mornings.',
    sunOnWall: 'Morning sun; no shade until midday',
    bestIn: 'cool',
  },
  {
    id: 'mt-beckworth',
    name: 'Mt Beckworth',
    area: 'Clunes',
    lat: -37.3022,
    lon: 143.7356,
    elevation: 634,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '1h45',
    trip: 'day',
    notes: 'Fine-grained granite tors above Clunes — slabs, cracks, and boulders scattered around the Main Group. Classics include Quartz Route (17), Cozy Corner (13), and harder slabs like New Kid In Town (20). The Crag tags Main Wall and Main Group as "all day sun" — very exposed, bakes in summer. Friendly skin-feel granite, dries within hours.',
    sunOnWall: 'All day (very exposed)',
    bestIn: 'cool',
  },
  {
    id: 'staughton-vale',
    name: 'Staughton Vale',
    area: 'Brisbane Ranges',
    lat: -37.7972,
    lon: 144.3308,
    elevation: 250,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '1h15',
    trip: 'day',
    notes: '30m sandstone cliff above the Brisbane Ranges — mostly top-rope from fixed anchors, with classics like First Commandment (18) and Leather Zen (19). Gym-like chunky holds on a gentle slab. West-facing — afternoon sun. CLOSED 1 Aug – 30 Nov for peregrine falcon breeding (Parks Vic).',
    sunOnWall: 'Afternoon (west-facing)',
    bestIn: 'mild',
    closedMonths: [8, 9, 10, 11],
    closureReason: 'peregrine breeding (Aug–Nov)',
  },
  {
    id: 'mt-alexander',
    name: 'Mt Alexander',
    area: 'Harcourt',
    lat: -36.9977,
    lon: 144.3049,
    elevation: 740,
    aspect: 'NE',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '1h30',
    trip: 'day',
    notes: 'Currently closed due to fire damage. Granodiorite slabs, cracks, and bouldering scattered around the hill near Harcourt. Dog Rocks and Wabbit Wocks are the classic introductions. Multi-aspect — plenty of options for sun or shade. Dries fast.',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'fire damage',
  },
  {
    id: 'harcourt-dogrocks',
    name: 'Dog Rocks',
    parentId: 'mt-alexander',
    area: 'Harcourt',
    lat: -37.0089,
    lon: 144.2864,
    elevation: 530,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '1h30',
    trip: 'day',
    notes: 'Roadside boulders and short walls on the western flank. North-facing — sun all day, ideal in cooler months. Dries within hours.',
    bestIn: 'cool',
    closedAll: true,
    closureReason: 'fire damage',
  },
  {
    id: 'harcourt-wabbitwocks',
    name: 'Wabbit Wocks',
    parentId: 'mt-alexander',
    area: 'Harcourt',
    lat: -37.0023,
    lon: 144.3081,
    elevation: 660,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '1h35',
    trip: 'day',
    notes: 'Compact slabs and short faces above the Dog Rocks pull-off. Morning sun, afternoon shade. A classic mid-grade introduction to Harcourt granite.',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'fire damage',
  },
  {
    id: 'harcourt-scorpionrocks',
    name: 'Scorpion Rocks',
    parentId: 'mt-alexander',
    area: 'Harcourt',
    lat: -36.9858,
    lon: 144.2839,
    elevation: 580,
    aspect: 'SW',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '1h40',
    trip: 'day',
    notes: 'Quieter Sutton Grange-side area with sport and bouldering. SW aspect — afternoon sun, morning shade. Good summer afternoon refuge from the Dog Rocks bake.',
    bestIn: 'warm',
    closedAll: true,
    closureReason: 'fire damage',
  },

  // — Arapiles sub-areas —
  {
    id: 'arap-main',
    name: 'Mt Arapiles',
    area: 'Mt Arapiles',
    lat: -36.7556,
    lon: 141.8403,
    elevation: 380,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'mixed',
    driveTime: '4h',
    trip: 'both',
    notes: 'Australia\'s premier trad crag. Front cliff faces NE/E — morning sun, afternoon shade. ~2000 routes from easy to 32. Dries fast on quartzite. 4h drive — usually a weekend, but check sub-crags for today\'s conditions.',
    sunOnWall: 'Morning only (main east-facing cliff)',
    bestIn: 'cool',
  },
  {
    id: 'arap-bard',
    parentId: 'arap-main',
    name: 'Bard Buttress',
    area: 'Mt Arapiles',
    lat: -36.7569,
    lon: 141.8431,
    elevation: 360,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Trad mecca. East face of the buttress catches early morning light, shades up by midday. Best in mild-to-cool conditions when other walls bake.',
    sunOnWall: 'Morning only (early morning light)',
    bestIn: 'cool',
  },
  {
    id: 'arap-tigerwall',
    parentId: 'arap-main',
    name: 'Tiger Wall',
    area: 'Mt Arapiles',
    lat: -36.7547,
    lon: 141.8442,
    elevation: 380,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 18],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Steep, fierce. More north-facing than the NE tag suggests — sun until around 4pm. Best in cool conditions.',
    sunOnWall: 'Sun until ~4pm',
    bestIn: 'cool',
  },
  {
    id: 'arap-pinnacleface',
    parentId: 'arap-main',
    name: 'The Pinnacle Face',
    area: 'Mt Arapiles',
    lat: -36.7540,
    lon: 141.8445,
    elevation: 385,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Main front cliff face. North-facing — sun until around 4pm.',
    sunOnWall: 'Sun until ~4pm',
    bestIn: 'cool',
  },
  {
    id: 'arap-pharos-front',
    parentId: 'arap-main',
    name: 'Pharos Front Wall',
    area: 'Mt Arapiles',
    lat: -36.7517,
    lon: 141.8458,
    elevation: 400,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'North-facing front face of The Pharos — sun until mid-afternoon. Long, alpine-feeling lines at the higher grades.',
    sunOnWall: 'Sun until mid-afternoon',
    bestIn: 'cool',
  },
  {
    id: 'arap-pharos-back',
    parentId: 'arap-main',
    name: 'Pharos Back Wall',
    area: 'Mt Arapiles',
    lat: -36.7520,
    lon: 141.8460,
    elevation: 400,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [14, 28],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'South-facing back face of The Pharos — shaded all day. Classic summer heat refuge at Arapiles.',
    sunOnWall: 'Shaded all day',
    bestIn: 'warm',
  },
  {
    id: 'arap-mitre',
    parentId: 'arap-main',
    name: 'Mitre Rock',
    area: 'Mt Arapiles',
    lat: -36.7314,
    lon: 141.8400,
    elevation: 320,
    aspect: 'W',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Quieter than the main mountain. Split N–S — east face catches morning sun, west face afternoon. Pick the shaded side in summer.',
    sunOnWall: 'Afternoon (west side); east side gets morning',
    bestIn: 'cool',
  },
  {
    id: 'arap-northern',
    parentId: 'arap-main',
    name: 'Northern Group',
    area: 'Mt Arapiles',
    lat: -36.7497,
    lon: 141.8403,
    elevation: 380,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Kachoong and the northern end of the front cliff. East-facing — best light at sunrise, afternoon shade.',
    sunOnWall: 'Morning only (best light at sunrise)',
    bestIn: 'cool',
  },
  {
    id: 'arap-henrybolte',
    parentId: 'arap-main',
    name: 'Henry Bolte Wall',
    area: 'Mt Arapiles',
    lat: -36.7500,
    lon: 141.8405,
    elevation: 380,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [14, 28],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Shaded all day — one of the best hot-weather options at Arapiles.',
    sunOnWall: 'Shaded all day',
    bestIn: 'warm',
  },

  {
    id: 'arap-cgleft',
    parentId: 'arap-main',
    name: 'Central Gully Left',
    area: 'Mt Arapiles',
    lat: -36.7558,
    lon: 141.8408,
    elevation: 360,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Left (south) side of Central Gully — Golden Fleece Wall, Moby Dick Pinnacle, Charity Buttress. More north-facing than NE — sun until around 4pm. Walk from camp 5–15min.',
    sunOnWall: 'Sun until ~4pm',
    bestIn: 'cool',
  },
  {
    id: 'arap-cgright',
    parentId: 'arap-main',
    name: 'Central Gully Right',
    area: 'Mt Arapiles',
    lat: -36.7553,
    lon: 141.8398,
    elevation: 360,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [12, 28],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Right (north) side of Central Gully — entirely shaded all day in winter, shade until ~5pm in summer. Classic hot-day option. Dunes Buttress is the shadiest sub-area.',
    sunOnWall: 'Shaded all day (winter); shade until ~5pm (summer)',
    bestIn: 'warm',
  },
  {
    id: 'arap-organpipes',
    parentId: 'arap-main',
    name: 'Organ Pipes',
    area: 'Mt Arapiles',
    lat: -36.7544,
    lon: 141.8419,
    elevation: 380,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'The most popular multi-pitch area at Arapiles — close to camp. Long, parallel cracks. More north-facing than NE — sun until around 4pm. Watch for raptor nesting Sep–Dec on Cassandra/Eurydice/Harlequin Cracks.',
    sunOnWall: 'Sun until ~4pm',
    bestIn: 'cool',
  },
  {
    id: 'arap-watchtower',
    parentId: 'arap-main',
    name: 'Watchtower Faces',
    area: 'Mt Arapiles',
    lat: -36.7536,
    lon: 141.8425,
    elevation: 390,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 20],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Left and Right Watchtower Faces — home of Watchtower Crack. Left face sun until late afternoon; Right face shade until ~5pm. Raptor nesting closures possible Sep–Dec.',
    sunOnWall: 'Left: sun until late afternoon; Right: shade until ~5pm',
    bestIn: 'cool',
  },
  {
    id: 'arap-kingrat',
    parentId: 'arap-main',
    name: 'King Rat Gully',
    area: 'Mt Arapiles',
    lat: -36.7522,
    lon: 141.8430,
    elevation: 390,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Slander Wall, Skydiver Wall and friends — quieter gully north of the main cliff. S-facing — shaded after ~11am, all day in winter. One of the best hot-weather options at Arapiles.',
    sunOnWall: 'Sun until ~11am; shaded rest of day (all day in winter)',
    bestIn: 'warm',
  },
  {
    id: 'arap-piloterror',
    parentId: 'arap-main',
    name: 'Pilot Error Cliffs',
    area: 'Mt Arapiles',
    lat: -36.7505,
    lon: 141.8420,
    elevation: 380,
    aspect: 'NW',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Morning shade then sun from midday until mid-afternoon. Good shoulder-season wall when you want sun but not all day.',
    sunOnWall: 'Morning shade; sun from midday until mid-afternoon',
    bestIn: 'cool',
  },

  {
    id: 'arap-atridae',
    parentId: 'arap-main',
    name: 'The Atridae',
    area: 'Mt Arapiles',
    lat: -36.7515,
    lon: 141.8423,
    elevation: 380,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Steep wall between Pilot Error and the Organ Pipes. North-facing — sun until early afternoon. Quality moderate-to-hard trad.',
    sunOnWall: 'Sun until early afternoon',
    bestIn: 'cool',
  },
  {
    id: 'arap-fang',
    parentId: 'arap-main',
    name: 'Fang Buttress',
    area: 'Mt Arapiles',
    lat: -36.7548,
    lon: 141.8412,
    elevation: 370,
    aspect: 'SE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Fang Buttress and surrounds — between Bard and Tiger Wall. SE-facing — morning sun, shaded by early afternoon. Mix of trad and bolted lines, classic mid-grade buttress.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'arap-bluffmajor',
    parentId: 'arap-main',
    name: 'Bluff Major',
    area: 'Mt Arapiles',
    lat: -36.7530,
    lon: 141.8435,
    elevation: 325,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [8, 22],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Sun until mid to late afternoon. Good all-day option in cool conditions.',
    sunOnWall: 'Sun until mid to late afternoon',
    bestIn: 'cool',
  },
  {
    id: 'arap-bluffs',
    parentId: 'arap-main',
    name: 'The Bluffs South Side',
    area: 'Mt Arapiles',
    lat: -36.7535,
    lon: 141.8440,
    elevation: 320,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [14, 28],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'S-facing — shade until late afternoon, all day in winter. Summer heat refuge near the Bluffs car park.',
    sunOnWall: 'Shade until late afternoon (all day in winter)',
    bestIn: 'warm',
  },
  {
    id: 'arap-bushranger',
    parentId: 'arap-main',
    name: 'Bushranger Bluff',
    area: 'Mt Arapiles',
    lat: -36.7625,
    lon: 141.8410,
    elevation: 320,
    aspect: 'SW',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [10, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Small, short outcrop at Arapiles\' far south-eastern end — ~40 mostly trad routes up to 28m, popular for beginners. SW aspect catches afternoon sun.',
    sunOnWall: 'Afternoon (SW-facing)',
    bestIn: 'mild',
  },
  {
    id: 'arap-declaration',
    parentId: 'arap-main',
    name: 'Declaration Crag',
    area: 'Mt Arapiles',
    lat: -36.7595,
    lon: 141.8385,
    elevation: 340,
    aspect: 'NW',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Also known as Taylor\'s Rock — a NW-facing sheer orange wall 15m from the road. ~49 routes. CLOSED — cultural heritage protection.',
    sunOnWall: 'Late afternoon (shaded most of day)',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'cultural heritage (Parks Vic)',
  },
  {
    id: 'arap-colosseum',
    parentId: 'arap-main',
    name: 'Colosseum Wall',
    area: 'Mt Arapiles',
    lat: -36.7580,
    lon: 141.8410,
    elevation: 320,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Short, high-quality splitter cracks (Christian Crack, The Rack). ~49 routes. North-facing — sun until early afternoon.',
    sunOnWall: 'Sun until early afternoon',
    bestIn: 'cool',
  },
  {
    id: 'arap-castle',
    parentId: 'arap-main',
    name: 'Castle Crag',
    area: 'Mt Arapiles',
    lat: -36.7558,
    lon: 141.8385,
    elevation: 360,
    aspect: 'W',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Compact free-standing pillar opposite Tiger Wall — ~35 routes in the 20–26 range (Procol Harum, The Undertaker). Morning-shady, afternoon sun. CLOSED — cultural heritage protection.',
    sunOnWall: 'Afternoon only (W-facing)',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'cultural heritage (Parks Vic)',
  },
  {
    id: 'arap-grotto',
    parentId: 'arap-main',
    name: 'Grotto Wall',
    area: 'Mt Arapiles',
    lat: -36.7555,
    lon: 141.8388,
    elevation: 365,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 3,
    idealTemp: [12, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Shady little retreat from the summer sun, tucked behind Castle Crag and Death Row Pinnacle. ~49 routes. A cool option on hot days.',
    sunOnWall: 'Shaded most of day',
    bestIn: 'warm',
  },
  {
    id: 'arap-voodoo',
    parentId: 'arap-main',
    name: 'Voodoo Buttress',
    area: 'Mt Arapiles',
    lat: -36.7548,
    lon: 141.8395,
    elevation: 370,
    aspect: 'N',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [8, 22],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Fin-like faces on high-quality quartzite. North-facing — sun until late afternoon. ~129 routes. New Image Wall sub-area closed for cultural heritage.',
    sunOnWall: 'Sun until late afternoon',
    bestIn: 'cool',
  },
  {
    id: 'arap-farnorth',
    parentId: 'arap-main',
    name: 'Far North',
    area: 'Mt Arapiles',
    lat: -36.7470,
    lon: 141.8425,
    elevation: 340,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Remote trad area beyond the Northern Group — ~214 routes offering solitude and harder climbing. NE-facing, morning sun. Several sub-walls (Intrepid Gully, Leasehold Wall, Werewolf Area) are closed for cultural heritage; full closure Sep–Dec for raptor nesting.',
    sunOnWall: 'Morning only (NE-facing)',
    bestIn: 'cool',
    closedMonths: [9, 10, 11, 12],
    closureReason: 'raptor nesting (Sep–Dec) + partial cultural heritage closures',
  },
  {
    id: 'arap-western',
    parentId: 'arap-main',
    name: 'Western Side',
    area: 'Mt Arapiles',
    lat: -36.7560,
    lon: 141.8350,
    elevation: 330,
    aspect: 'W',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Obscure wilderness trad with a Grampians feel — ~200 routes. W-facing, afternoon sun. CLOSED — total ban under 2024/25 Parks Victoria cultural heritage protections.',
    sunOnWall: 'Afternoon (W-facing)',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'cultural heritage (Parks Vic 2024/25)',
  },

  // — Grampians sub-areas —
  {
    id: 'gramps-main',
    name: 'Grampians',
    area: 'Grampians',
    lat: -37.1389,
    lon: 142.5217,
    elevation: 250,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 24],
    shade: 'mixed',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Sandstone megacrag spanning Northern (Stapylton, Taipan), Central (Bundaleer, Muline) and Western (Vic Range) sub-areas. Slower to dry after rain than Arapiles. Wide range of aspects across sub-crags — pick the right wall for the conditions.',
    bestIn: 'mild',
  },
  {
    id: 'gramps-stapylton',
    parentId: 'gramps-main',
    name: 'Mt Stapylton',
    area: 'Grampians (Northern)',
    lat: -36.9036,
    lon: 142.4131,
    elevation: 460,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'World-class bouldering and short sport on the main escarpment. West-facing — afternoon sun, harsh in summer. Dries reasonably fast in wind.',
    sunOnWall: 'Afternoon (late afternoon in summer, from midday in winter)',
    bestIn: 'cool',
  },
  {
    id: 'gramps-taipan',
    parentId: 'gramps-main',
    name: 'Taipan Wall',
    area: 'Grampians (Northern)',
    lat: -36.9100,
    lon: 142.4239,
    elevation: 480,
    aspect: 'NW',
    rockType: 'sandstone',
    dryRating: 5,
    idealTemp: [17, 22],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Steep orange wave of rock. NW-facing — shaded until around 2pm, then afternoon sun. Ideal temps 17–22°C. Dries fast in wind.',
    sunOnWall: 'Shaded until ~2pm; afternoon sun',
    bestIn: 'cool',
  },
  {
    id: 'gramps-bundaleer',
    parentId: 'gramps-main',
    name: 'Bundaleer',
    area: 'Grampians (Central)',
    lat: -37.1453,
    lon: 142.5269,
    elevation: 700,
    aspect: 'N',
    rockType: 'sandstone',
    dryRating: 2,
    idealTemp: [8, 20],
    shade: 'none',
    driveTime: '4h',
    trip: 'both',
    notes: 'Extensive north-facing cliff line. All day sun — avoid in summer heat. Holds moisture; needs 2-3 dry days to come into condition.',
    sunOnWall: 'All day',
    bestIn: 'cool',
  },
  {
    id: 'gramps-muline',
    parentId: 'gramps-main',
    name: 'Muline',
    area: 'Grampians (Central)',
    lat: -37.1672,
    lon: 142.5300,
    elevation: 650,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 3,
    closedAll: true,
    closureReason: 'Closed as of 2026',
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Closed as of 2026. Vertical to slightly overhung sport. Muline Cave gets afternoon sun — best on cool afternoons. Allow 24h to dry after rain.',
    sunOnWall: 'Afternoon only',
    bestIn: 'cool',
  },
  {
    id: 'gramps-vicrange',
    parentId: 'gramps-main',
    name: 'Victoria Range',
    area: 'Grampians (Western)',
    lat: -37.2700,
    lon: 142.3833,
    elevation: 550,
    aspect: 'NE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [8, 20],
    shade: 'afternoon',
    driveTime: '4h15',
    trip: 'both',
    notes: 'Remote, less-trafficked. Scarp faces point east; NE aspect catches morning through mid-afternoon sun. Good in cool to mild conditions.',
    sunOnWall: 'Morning until mid-afternoon',
    bestIn: 'cool',
  },
  {
    id: 'gramps-guardhouse',
    parentId: 'gramps-main',
    name: 'The Guardhouse',
    area: 'Grampians (Western)',
    lat: -37.3017,
    lon: 142.3892,
    elevation: 480,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [8, 20],
    shade: 'morning',
    driveTime: '4h15',
    trip: 'both',
    notes: 'Compact Victoria Range cliff with concentrated quality sport in the mid-grades. West-facing — sun hits the wall from around 2pm in summer. Preferred in cooler weather.',
    sunOnWall: 'Afternoon (after ~2pm in summer)',
    bestIn: 'cool',
  },
  {
    id: 'gramps-rosea',
    parentId: 'gramps-main',
    name: 'Mt Rosea',
    area: 'Grampians (Central)',
    lat: -37.2333,
    lon: 142.4833,
    elevation: 1000,
    aspect: 'NE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [6, 18],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'High elevation = cooler. Long alpine-style routes; NE-facing, good for all but the hottest weather. Goes into shade mid-afternoon. Approach is serious.',
    sunOnWall: 'Morning until mid-afternoon',
    bestIn: 'cool',
  },
  {
    id: 'gramps-westflank',
    parentId: 'gramps-main',
    name: 'West Flank',
    area: 'Grampians (Northern)',
    lat: -36.8934,
    lon: 142.3754,
    elevation: 270,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 5,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Good hot-weather option — west-facing sport cliff shaded until afternoon. Popular for summer mornings. Variety of grades, mostly bolted. Below Taipan Wall.',
    sunOnWall: 'Afternoon only (shade until early/mid afternoon)',
    bestIn: 'warm',
  },
  {
    id: 'gramps-iforget',
    parentId: 'gramps-main',
    name: 'I Forget Walls',
    area: 'Grampians (Northern)',
    lat: -36.8945,
    lon: 142.3845,
    elevation: 280,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Popular moderate sport crag, 30-min walk from Stapylton Campground. West-facing — shaded in the morning, afternoon sun. Bring helmet — some loose rock and lines still being cleaned.',
    sunOnWall: 'Afternoon only',
    bestIn: 'mild',
  },
  {
    id: 'gramps-ravine',
    parentId: 'gramps-main',
    name: 'The Ravine',
    area: 'Grampians (Northern)',
    lat: -36.9020,
    lon: 142.4080,
    elevation: 350,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [12, 24],
    shade: 'afternoon',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Hidden canyon east of the olive plantation. East-facing — very shady, great hot-weather option. North cave is steep sport. Lush valley, slow to dry. Mosquitoes — bring repellent.',
    sunOnWall: 'Morning only',
    bestIn: 'warm',
  },
  {
    id: 'gramps-vandiemens',
    parentId: 'gramps-main',
    name: "Van Diemen's Land",
    area: 'Grampians (Northern)',
    lat: -36.8936,
    lon: 142.3855,
    elevation: 320,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 5,
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Steep sport amphitheatre at Hollow Mountain — shade in morning then very sunny. Several excellent grade 22–26s. Best in cool weather; warm afternoons.',
    sunOnWall: 'Afternoon only',
    bestIn: 'cool',
  },
  {
    id: 'gramps-dreamtime',
    parentId: 'gramps-main',
    name: 'Dreamtime Wall',
    area: 'Grampians (Northern)',
    lat: -36.8985,
    lon: 142.3920,
    elevation: 340,
    aspect: 'N',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [4, 16],
    shade: 'none',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Striking steep wall east of Mt Stapylton — home of Dreamtime and several elite sport routes. North-facing — winter sun all day. Cultural-heritage closures may apply on some lines — check Parks Vic before climbing.',
    sunOnWall: 'Most of the day (north-facing, winter sun)',
    bestIn: 'cold',
  },
  {
    id: 'gramps-hallsgap',
    parentId: 'gramps-main',
    name: 'Halls Gap Area',
    area: 'Grampians (Central)',
    lat: -37.1372,
    lon: 142.5235,
    elevation: 280,
    aspect: 'SE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [10, 24],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Scattered easy-access cliffs around Halls Gap valley — The Watchtower, Sundial, Punter’s Pinnacle. Slabby short routes plus bouldering at Venus Baths. SE/E-facing, mostly morning sun. Good rainy-day backup with quick approaches.',
    sunOnWall: 'Morning only',
    bestIn: 'mild',
  },

  // — Mt Buffalo —
  {
    id: 'buffalo-main',
    name: 'Mt Buffalo',
    area: 'Mt Buffalo',
    lat: -36.7367,
    lon: 146.8153,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 24],
    shade: 'mixed',
    driveTime: '4h',
    trip: 'both',
    notes: 'High-altitude granite plateau (1500m+). Cooler than the plains — summer refuge. Watch weather closely: storms move fast above the treeline. Multi-pitch trad on The Cathedral, sport at Eurobin Falls.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-cathedral',
    parentId: 'buffalo-main',
    name: 'The Cathedral',
    area: 'Mt Buffalo',
    lat: -36.7367,
    lon: 146.8153,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Iconic alpine granite tor on the Buffalo plateau. Mostly trad with the odd sport route. Best in summer — high elevation means cold, snow possible Apr–Oct. Approach via Cathedral–Hump track. Long days.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-hump',
    parentId: 'buffalo-main',
    name: 'The Hump Area',
    area: 'Mt Buffalo',
    lat: -36.7383,
    lon: 146.8158,
    elevation: 1695,
    aspect: 'SW',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Highest point on the plateau \u2014 long granite walls, mixed sport and trad. Can be windy and exposed. Summer-only realistically. Spectacular position.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-eurobin',
    parentId: 'buffalo-main',
    name: 'Eurobin Falls',
    area: 'Mt Buffalo',
    lat: -36.7611,
    lon: 146.8261,
    elevation: 480,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 2,
    idealTemp: [12, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Polished water-washed granite slabs at the base of the mountain \u2014 several degrees warmer than the plateau. Sun nearly all morning. Slow to dry, best left for drier seasons. Swimming holes at the base. Long easy slabs (grades 14\u201324).',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-mackeys',
    parentId: 'buffalo-main',
    name: 'Mackeys Lookout',
    area: 'Mt Buffalo',
    lat: -36.7250,
    lon: 146.7950,
    elevation: 1400,
    aspect: 'NW',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Big multi-pitch trad and sport on the western edge of the plateau. NW aspect catches afternoon sun. Up to 240m walls. Long days, committing approaches.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-mcleod',
    parentId: 'buffalo-main',
    name: 'Mt McLeod',
    area: 'Mt Buffalo',
    lat: -36.6944,
    lon: 146.8367,
    elevation: 1600,
    aspect: 'S',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [14, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Remote northern end of the plateau \u2014 several km walk-in via Rocky Creek. Free remote camping. South-facing, shady, stays cool. Up to 160m walls. For when you want solitude.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-gorge-south',
    parentId: 'buffalo-main',
    name: 'The Gorge \u2013 South Side',
    area: 'Mt Buffalo',
    lat: -36.7414,
    lon: 146.8089,
    elevation: 1300,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '4h',
    trip: 'both',
    notes: 'Sunny north-facing side of the gorge \u2014 224 routes including \u201cWhere Angels Fear To Tread\u201d (263m grade 17). Hang-glider lookout access, abseil approaches common. Sun all day, can bake in summer.',
    bestIn: 'cool',
  },
  {
    id: 'buffalo-gorge-north',
    parentId: 'buffalo-main',
    name: 'The Gorge \u2013 North Side',
    area: 'Mt Buffalo',
    lat: -36.7367,
    lon: 146.8083,
    elevation: 1300,
    aspect: 'S',
    rockType: 'granite',
    dryRating: 3,
    idealTemp: [14, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'The famous North Wall \u2014 home to Ozymandias (280m) and Australia\u2019s biggest aid lines. Shady, cold, holds moisture. Some winter aid climbing possible. Up to 110m. Adventure terrain.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-reservoir',
    parentId: 'buffalo-main',
    name: 'Reservoir Environs',
    area: 'Mt Buffalo',
    lat: -36.7444,
    lon: 146.8125,
    elevation: 1320,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 24],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Short single-pitch trad and slabs near the reservoir. Easy access. East-facing \u2014 sunny mornings, shady afternoons. Up to 22m. Good warm-up venue.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-catani',
    parentId: 'buffalo-main',
    name: 'Lake Catani',
    area: 'Mt Buffalo',
    lat: -36.7456,
    lon: 146.8086,
    elevation: 1310,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 22],
    shade: 'late-afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Catani slabs \u2014 beginner-friendly short routes near the campground. 82 routes up to 24m. Easy walk-in from the campsite. Good for warm-ups and rest days.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-lesouef',
    parentId: 'buffalo-main',
    name: 'Le Souef Plateau',
    area: 'Mt Buffalo',
    lat: -36.7300,
    lon: 146.8200,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Plateau crag with mixed trad and sport, 53 routes up to 22m. West-facing afternoon sun. Quieter alternative to the popular trade crags.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-buckland',
    parentId: 'buffalo-main',
    name: 'Buckland Slabs',
    area: 'Mt Buffalo',
    lat: -36.7800,
    lon: 146.7700,
    elevation: 600,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Lower-elevation granite slabs in the Buckland Valley below the plateau. North-facing \u2014 sun all day, warmer than the plateau. Dries fast. Up to 57m. Useful when the top is socked-in.',
    bestIn: 'cool',
  },
  {
    id: 'buffalo-tatra',
    parentId: 'buffalo-main',
    name: 'Tatra Rocks',
    area: 'Mt Buffalo',
    lat: -36.7350,
    lon: 146.8050,
    elevation: 1450,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Easy-access plateau crag near the old Tatra Inn site. 30 routes up to 24m. East-facing \u2014 morning sun, cooler afternoons. Mixed trad and sport.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-backwall',
    parentId: 'buffalo-main',
    name: 'The Back Wall Area',
    area: 'Mt Buffalo',
    lat: -36.7320,
    lon: 146.8170,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 3,
    idealTemp: [10, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Big shady south-facing wall with trad and aid lines up to 110m. Cool, holds moisture. For long days when the sunny crags are too hot.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-horn',
    parentId: 'buffalo-main',
    name: 'The Horn Area',
    area: 'Mt Buffalo',
    lat: -36.7458,
    lon: 146.8378,
    elevation: 1723,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Sharp granite at the road\u2019s end \u2014 the Horn summit (1723m, highest on the plateau). 113 routes, mostly short trad and sport with bolts. Classic intro: Peroxide Blonde (gr 20 ar\u00eate). Wind-blasted, dries fast. West-facing afternoon sun.',
    bestIn: 'warm',
  },
];

// Group crags by parent area for the UI summary
export const AREAS = {
  'Mt Macedon': ['camels-hump', 'ben-cairn'],
  'Werribee Gorge': ['falcons-lookout'],
  'Cathedral Ranges': ['cathedral-main', 'cathedral-balcony', 'cathedral-sugarloaf', 'cathedral-northjawbone', 'cathedral-southjawbone'],
  'You Yangs': ['youyangs-main', 'youyangs-flatrock', 'youyangs-gravelpit', 'youyangs-royaltywalls', 'youyangs-adamblock', 'youyangs-urinalwall', 'youyangs-flindersslabs'],
  'Clunes': ['mt-beckworth'],
  'Brisbane Ranges': ['staughton-vale'],
  'Harcourt': ['mt-alexander', 'harcourt-dogrocks', 'harcourt-wabbitwocks', 'harcourt-scorpionrocks'],
  'Mt Arapiles': ['arap-main', 'arap-cgleft', 'arap-cgright', 'arap-bard', 'arap-fang', 'arap-organpipes', 'arap-atridae', 'arap-watchtower', 'arap-kingrat', 'arap-piloterror', 'arap-tigerwall', 'arap-pinnacleface', 'arap-pharos-front', 'arap-pharos-back', 'arap-bluffmajor', 'arap-bluffs', 'arap-mitre', 'arap-northern', 'arap-henrybolte', 'arap-bushranger', 'arap-declaration', 'arap-colosseum', 'arap-castle', 'arap-grotto', 'arap-voodoo', 'arap-farnorth', 'arap-western'],
  'Grampians': ['gramps-main', 'gramps-stapylton', 'gramps-taipan', 'gramps-dreamtime', 'gramps-bundaleer', 'gramps-muline', 'gramps-vicrange', 'gramps-guardhouse', 'gramps-rosea', 'gramps-westflank', 'gramps-iforget', 'gramps-ravine', 'gramps-vandiemens', 'gramps-hallsgap'],
  'Mt Buffalo': ['buffalo-main', 'buffalo-cathedral', 'buffalo-hump', 'buffalo-eurobin', 'buffalo-mackeys', 'buffalo-mcleod', 'buffalo-gorge-south', 'buffalo-gorge-north', 'buffalo-reservoir', 'buffalo-catani', 'buffalo-lesouef', 'buffalo-buckland', 'buffalo-tatra', 'buffalo-backwall', 'buffalo-horn'],
};
