// Crag database — Melbourne climber's regular destinations
// Each crag has lat/lon, aspect, elevation, dry-out time, and notes.
// Sub-areas where it matters (Arapiles, Grampians).
//
// Aspect codes: N, NE, E, SE, S, SW, W, NW
// dryRating: 1 (slow to dry, holds moisture) → 5 (very fast, dries in hours)
// idealTemp: [min, max] °C — sweet spot for friction & comfort
// shade: "morning", "afternoon", "all-day", "none" — when shade is available
// rockType: granite, sandstone, quartzite — used for context
// trip: "day" (<3h drive, day-trip from Melbourne) or "weekend" (3h+, overnight worth it)

export const CRAGS = [
  // — Metro / day-trip —
  {
    id: 'camels-hump',
    name: "Camel's Hump",
    area: 'Mt Macedon',
    lat: -37.3947,
    lon: 144.5547,
    elevation: 950,
    aspect: 'W',
    rockType: 'trachyte',
    dryRating: 4,
    idealTemp: [8, 18],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'High elevation keeps it cooler than the city. Trad-heavy on Omega Block — south- and west-facing sectors. Much of the crag is shaded by forest. Dries quickly after rain — a few hours of sun and wind.',
    sunOnWall: 'Afternoon (Omega Block); forest-shaded otherwise',
    bestIn: 'cool',
  },
  {
    id: 'falcons-lookout',
    name: 'Falcons Lookout',
    area: 'Werribee Gorge',
    lat: -37.6736,
    lon: 144.4322,
    elevation: 250,
    aspect: 'N',
    rockType: 'conglomerate',
    dryRating: 3,
    idealTemp: [10, 20],
    shade: 'none',
    driveTime: '50min',
    trip: 'day',
    notes: 'North-facing — catches sun most of the day. Best in cooler months; can be hot in summer. Conglomerate dries reasonably fast in sun and wind.',
    sunOnWall: 'Most of the day (north-facing)',
    bestIn: 'cool',
  },
  {
    id: 'cathedral-balcony',
    name: 'The Balcony',
    area: 'Cathedral Ranges',
    lat: -37.3667,
    lon: 145.7472,
    elevation: 940,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [8, 18],
    shade: 'afternoon',
    driveTime: '1h45',
    trip: 'both',
    notes: 'Exposed ridge-top crag with a mix of sport and trad. East aspect catches morning sun then shades up by midday — versatile across seasons. Dries fast in wind. Approach is committing.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'youyangs-main',
    name: 'You Yangs',
    area: 'You Yangs',
    lat: -37.9489,
    lon: 144.4297,
    elevation: 320,
    aspect: 'NW',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 20],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'Granite slabs and aretes. Big Rock Main Face is WNW — morning shade, afternoon roast. Dries within hours. Get there early in summer.',
    sunOnWall: 'Afternoon (morning shade)',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-flatrock',
    name: 'Flat Rock',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9531,
    lon: 144.4250,
    elevation: 280,
    aspect: 'SE',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [12, 22],
    shade: 'afternoon',
    driveTime: '1h',
    trip: 'day',
    notes: 'Bouldering-heavy area. Faster-drying than Main. SE aspect = cooler in afternoon.',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-gravelpit',
    name: 'Gravel Pit Tor',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9461,
    lon: 144.4262,
    elevation: 300,
    aspect: 'SE',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 20],
    shade: 'afternoon',
    driveTime: '1h',
    trip: 'day',
    notes: 'Stand-alone monolith with the steepest sport routes in the park — Edging Bets, A Question of Ethics, Silver Knight. SE-facing main wall: morning sun then shade by midday. Granite dries within hours.',
    bestIn: 'mild',
  },
  {
    id: 'youyangs-royaltywalls',
    name: 'Royalty Walls',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9512,
    lon: 144.4231,
    elevation: 290,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 20],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'Lesser-trafficked walls with a mix of slabs and short faces. West-facing — afternoon sun, cooler mornings. Good when Gravel Pit is busy or wet.',
    bestIn: 'cool',
  },
  {
    id: 'youyangs-adamblock',
    name: 'Adam Block',
    parentId: 'youyangs-main',
    area: 'You Yangs',
    lat: -37.9495,
    lon: 144.4283,
    elevation: 310,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [8, 18],
    shade: 'morning',
    driveTime: '1h',
    trip: 'day',
    notes: 'Compact block in the Saddle Area. Home to the classic line Adam (26) — a left-trending crack capped by an offwidth through a roof. West aspect catches afternoon sun; best on cooler days when the crack is dry.',
    bestIn: 'cool',
  },
  {
    id: 'mt-beckworth',
    name: 'Mt Beckworth',
    area: 'Clunes',
    lat: -37.3022,
    lon: 143.7356,
    elevation: 634,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '1h45',
    trip: 'day',
    notes: 'Fine-grained granite tors above Clunes — slabs, cracks, and boulders scattered around the Main Group. Classics include Quartz Route (17), Cozy Corner (13), and harder slabs like New Kid In Town (20). The Crag tags Main Wall and Main Group as "all day sun" — very exposed, bakes in summer. Friendly skin-feel granite, dries within hours.',
    sunOnWall: 'All day (very exposed)',
    bestIn: 'cool',
  },
  {
    id: 'staughton-vale',
    name: 'Staughton Vale',
    area: 'Brisbane Ranges',
    lat: -37.7972,
    lon: 144.3308,
    elevation: 250,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '1h15',
    trip: 'day',
    notes: '30m sandstone cliff above the Brisbane Ranges — mostly top-rope from fixed anchors, with classics like First Commandment (18) and Leather Zen (19). Gym-like chunky holds on a gentle slab. West-facing — afternoon sun. CLOSED 1 Aug – 30 Nov for peregrine falcon breeding (Parks Vic).',
    sunOnWall: 'Afternoon (west-facing)',
    bestIn: 'mild',
    closedMonths: [8, 9, 10, 11],
    closureReason: 'peregrine breeding (Aug–Nov)',
  },
  {
    id: 'mt-alexander',
    name: 'Mt Alexander',
    area: 'Harcourt',
    lat: -36.9977,
    lon: 144.3049,
    elevation: 740,
    aspect: 'NE',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '1h30',
    trip: 'day',
    notes: 'Currently closed due to fire damage. Granodiorite slabs, cracks, and bouldering scattered around the hill near Harcourt. Dog Rocks and Wabbit Wocks are the classic introductions. Multi-aspect — plenty of options for sun or shade. Dries fast.',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'fire damage',
  },
  {
    id: 'harcourt-dogrocks',
    name: 'Dog Rocks',
    parentId: 'mt-alexander',
    area: 'Harcourt',
    lat: -37.0089,
    lon: 144.2864,
    elevation: 530,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '1h30',
    trip: 'day',
    notes: 'Roadside boulders and short walls on the western flank. North-facing — sun all day, ideal in cooler months. Dries within hours.',
    bestIn: 'cool',
    closedAll: true,
    closureReason: 'fire damage',
  },
  {
    id: 'harcourt-wabbitwocks',
    name: 'Wabbit Wocks',
    parentId: 'mt-alexander',
    area: 'Harcourt',
    lat: -37.0023,
    lon: 144.3081,
    elevation: 660,
    aspect: 'NE',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '1h35',
    trip: 'day',
    notes: 'Compact slabs and short faces above the Dog Rocks pull-off. Morning sun, afternoon shade. A classic mid-grade introduction to Harcourt granite.',
    bestIn: 'mild',
    closedAll: true,
    closureReason: 'fire damage',
  },
  {
    id: 'harcourt-scorpionrocks',
    name: 'Scorpion Rocks',
    parentId: 'mt-alexander',
    area: 'Harcourt',
    lat: -36.9858,
    lon: 144.2839,
    elevation: 580,
    aspect: 'SW',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '1h40',
    trip: 'day',
    notes: 'Quieter Sutton Grange-side area with sport and bouldering. SW aspect — afternoon sun, morning shade. Good summer afternoon refuge from the Dog Rocks bake.',
    bestIn: 'warm',
    closedAll: true,
    closureReason: 'fire damage',
  },

  // — Arapiles sub-areas —
  {
    id: 'arap-main',
    name: 'Mt Arapiles',
    area: 'Mt Arapiles',
    lat: -36.7556,
    lon: 141.8403,
    elevation: 380,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'mixed',
    driveTime: '4h',
    trip: 'both',
    notes: 'Australia\'s premier trad crag. Front cliff faces NE/E — morning sun, afternoon shade. ~2000 routes from easy to 32. Dries fast on quartzite. 4h drive — usually a weekend, but check sub-crags for today\'s conditions.',
    sunOnWall: 'Morning only (main east-facing cliff)',
    bestIn: 'cool',
  },
  {
    id: 'arap-central',
    parentId: 'arap-main',
    name: 'Central Gully',
    area: 'Mt Arapiles',
    lat: -36.7556,
    lon: 141.8403,
    elevation: 360,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'The classics: Punks, Kachoong, Watchtower Crack. Morning sun, afternoon shade. Dries within hours.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'arap-bard',
    parentId: 'arap-main',
    name: 'Bard Buttress',
    area: 'Mt Arapiles',
    lat: -36.7569,
    lon: 141.8431,
    elevation: 360,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Trad mecca. East face of the buttress catches early morning light, shades up by midday. Best in mild-to-cool conditions when other walls bake.',
    sunOnWall: 'Morning only (early morning light)',
    bestIn: 'cool',
  },
  {
    id: 'arap-tigerwall',
    parentId: 'arap-main',
    name: 'Tiger Wall',
    area: 'Mt Arapiles',
    lat: -36.7547,
    lon: 141.8442,
    elevation: 380,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 18],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Steep, fierce. NE-facing — morning sun, shaded in the afternoon. Best in cool conditions.',
    sunOnWall: 'Morning only (shaded in afternoon)',
    bestIn: 'cool',
  },
  {
    id: 'arap-pharos',
    parentId: 'arap-main',
    name: 'The Pharos',
    area: 'Mt Arapiles',
    lat: -36.7517,
    lon: 141.8458,
    elevation: 400,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [12, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'South-facing — the summer/heat refuge of Arapiles. Back Wall (S/SW) and South Face (SE) hold the most popular routes. Long, alpine-feeling lines.',
    sunOnWall: 'Mostly shaded all day',
    bestIn: 'warm',
  },
  {
    id: 'arap-mitre',
    parentId: 'arap-main',
    name: 'Mitre Rock',
    area: 'Mt Arapiles',
    lat: -36.7314,
    lon: 141.8400,
    elevation: 320,
    aspect: 'W',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Quieter than the main mountain. Split N–S — east face catches morning sun, west face afternoon. Pick the shaded side in summer.',
    sunOnWall: 'Afternoon (west side); east side gets morning',
    bestIn: 'cool',
  },
  {
    id: 'arap-northern',
    parentId: 'arap-main',
    name: 'Northern Group',
    area: 'Mt Arapiles',
    lat: -36.7497,
    lon: 141.8403,
    elevation: 380,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Kachoong, Henry Bolte Wall and the northern end of the front cliff. East-facing — best light at sunrise, afternoon shade.',
    sunOnWall: 'Morning only (best light at sunrise)',
    bestIn: 'cool',
  },

  {
    id: 'arap-cgleft',
    parentId: 'arap-main',
    name: 'Central Gully Left',
    area: 'Mt Arapiles',
    lat: -36.7558,
    lon: 141.8408,
    elevation: 360,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Left (south) side of Central Gully — Golden Fleece Wall, Moby Dick Pinnacle, Charity Buttress. NE-facing, sun-soaked in winter mornings, shaded by afternoon. Walk from camp 5–15min.',
    sunOnWall: 'Morning only (winter sun)',
    bestIn: 'cool',
  },
  {
    id: 'arap-cgright',
    parentId: 'arap-main',
    name: 'Central Gully Right',
    area: 'Mt Arapiles',
    lat: -36.7553,
    lon: 141.8398,
    elevation: 360,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Right (north) side of Central Gully — direct walk-in from camp. Morning sun, shades up by midday. Dunes Buttress is notably shady. Some classics in the moderate grades.',
    sunOnWall: 'Morning only (some sub-areas notably shady)',
    bestIn: 'cool',
  },
  {
    id: 'arap-organpipes',
    parentId: 'arap-main',
    name: 'Organ Pipes',
    area: 'Mt Arapiles',
    lat: -36.7544,
    lon: 141.8419,
    elevation: 380,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [6, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'The most popular multi-pitch area at Arapiles — close to camp. Long, parallel cracks. NE-facing: morning sun, afternoon shade. Watch for raptor nesting Sep–Dec on Cassandra/Eurydice/Harlequin Cracks.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'arap-watchtower',
    parentId: 'arap-main',
    name: 'Watchtower Faces',
    area: 'Mt Arapiles',
    lat: -36.7536,
    lon: 141.8425,
    elevation: 390,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Left and Right Watchtower Faces — home of Watchtower Crack. Steep cracks and faces. Morning sun, afternoon shade. Raptor nesting closures possible Sep–Dec.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'arap-kingrat',
    parentId: 'arap-main',
    name: 'King Rat Gully',
    area: 'Mt Arapiles',
    lat: -36.7522,
    lon: 141.8430,
    elevation: 390,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [12, 24],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Slander Wall, Skydiver Wall and friends — quieter gully north of the main cliff. Main walls face south and stay shaded — a hot-day option. Mix of moderate trad and harder lines.',
    sunOnWall: 'Shaded most of the day',
    bestIn: 'warm',
  },
  {
    id: 'arap-piloterror',
    parentId: 'arap-main',
    name: 'Pilot Error Area',
    area: 'Mt Arapiles',
    lat: -36.7505,
    lon: 141.8420,
    elevation: 380,
    aspect: 'NE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [10, 24],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Far-north outcrop with Baby Buttress, Cobwebs Gully and the Flight Deck nearby. NE-tagged but deep in a gully — main wall stays shady most of the day. A hot-day option.',
    sunOnWall: 'Always shady (deep gully despite NE tag)',
    bestIn: 'warm',
  },

  {
    id: 'arap-atridae',
    parentId: 'arap-main',
    name: 'Atridae',
    area: 'Mt Arapiles',
    lat: -36.7515,
    lon: 141.8423,
    elevation: 380,
    aspect: 'E',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Steep, photogenic wall between Pilot Error and the Organ Pipes. The Flight Deck (main wall) faces the campground. East-facing, sunrise light, afternoon shade. Quality moderate-to-hard trad.',
    sunOnWall: 'Morning only (sunrise)',
    bestIn: 'cool',
  },
  {
    id: 'arap-fang',
    parentId: 'arap-main',
    name: 'Fang Buttress',
    area: 'Mt Arapiles',
    lat: -36.7548,
    lon: 141.8412,
    elevation: 370,
    aspect: 'SE',
    rockType: 'quartzite',
    dryRating: 5,
    idealTemp: [8, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Fang Buttress and surrounds — between Bard and Tiger Wall. SE-facing — morning sun, shaded by early afternoon. Mix of trad and bolted lines, classic mid-grade buttress.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'arap-bluffs',
    parentId: 'arap-main',
    name: 'The Bluffs',
    area: 'Mt Arapiles',
    lat: -36.7530,
    lon: 141.8440,
    elevation: 320,
    aspect: 'S',
    rockType: 'quartzite',
    dryRating: 4,
    idealTemp: [12, 26],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'South-of-summit cliffs near the Bluffs car park. SW aspect catches afternoon sun — a useful warm-up zone in cooler weather. Drier than the main cliff after rain.',
    bestIn: 'mild',
  },

  // — Grampians sub-areas —
  {
    id: 'gramps-main',
    name: 'Grampians',
    area: 'Grampians',
    lat: -37.1389,
    lon: 142.5217,
    elevation: 250,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [10, 24],
    shade: 'mixed',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Sandstone megacrag spanning Northern (Stapylton, Taipan), Central (Bundaleer, Muline) and Western (Vic Range) sub-areas. Slower to dry after rain than Arapiles. Wide range of aspects across sub-crags — pick the right wall for the conditions.',
    bestIn: 'mild',
  },
  {
    id: 'gramps-stapylton',
    parentId: 'gramps-main',
    name: 'Mt Stapylton',
    area: 'Grampians (Northern)',
    lat: -36.9036,
    lon: 142.4131,
    elevation: 460,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'World-class bouldering and short sport on the main escarpment. West-facing — afternoon sun, harsh in summer. Dries reasonably fast in wind.',
    sunOnWall: 'Afternoon (late afternoon in summer, from midday in winter)',
    bestIn: 'cool',
  },
  {
    id: 'gramps-taipan',
    parentId: 'gramps-main',
    name: 'Taipan Wall',
    area: 'Grampians (Northern)',
    lat: -36.9100,
    lon: 142.4239,
    elevation: 480,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 5,
    idealTemp: [6, 16],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Steep orange wave of rock. Dries fast in wind. West-facing — afternoon sun, harsh in summer. Glorious in cold winter.',
    sunOnWall: 'Afternoon only',
    bestIn: 'cold',
  },
  {
    id: 'gramps-bundaleer',
    parentId: 'gramps-main',
    name: 'Bundaleer',
    area: 'Grampians (Central)',
    lat: -37.1453,
    lon: 142.5269,
    elevation: 700,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 2,
    idealTemp: [8, 20],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Extensive east-facing cliff line. Morning sun, afternoon shade — a summer crag. Holds moisture; needs 2-3 dry days to come into condition.',
    sunOnWall: 'Morning only',
    bestIn: 'warm',
  },
  {
    id: 'gramps-muline',
    parentId: 'gramps-main',
    name: 'Muline',
    area: 'Grampians (Central)',
    lat: -37.1672,
    lon: 142.5300,
    elevation: 650,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [6, 18],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Vertical to slightly overhung sport. Muline Cave gets afternoon sun — best on cool afternoons. Allow 24h to dry after rain.',
    sunOnWall: 'Afternoon only',
    bestIn: 'cool',
  },
  {
    id: 'gramps-vicrange',
    parentId: 'gramps-main',
    name: 'Victoria Range',
    area: 'Grampians (Western)',
    lat: -37.2700,
    lon: 142.3833,
    elevation: 550,
    aspect: 'NE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [8, 20],
    shade: 'afternoon',
    driveTime: '4h15',
    trip: 'both',
    notes: 'Remote, less-trafficked. Scarp faces point east; NE aspect catches morning through mid-afternoon sun. Good in cool to mild conditions.',
    sunOnWall: 'Morning until mid-afternoon',
    bestIn: 'cool',
  },
  {
    id: 'gramps-guardhouse',
    parentId: 'gramps-main',
    name: 'The Guardhouse',
    area: 'Grampians (Western)',
    lat: -37.3017,
    lon: 142.3892,
    elevation: 480,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [8, 20],
    shade: 'morning',
    driveTime: '4h15',
    trip: 'both',
    notes: 'Compact Victoria Range cliff with concentrated quality sport in the mid-grades. West-facing — sun hits the wall from around 2pm in summer. Preferred in cooler weather.',
    sunOnWall: 'Afternoon (after ~2pm in summer)',
    bestIn: 'cool',
  },
  {
    id: 'gramps-rosea',
    parentId: 'gramps-main',
    name: 'Mt Rosea',
    area: 'Grampians (Central)',
    lat: -37.2333,
    lon: 142.4833,
    elevation: 1000,
    aspect: 'NE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [6, 18],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'High elevation = cooler. Long alpine-style routes; NE-facing, good for all but the hottest weather. Goes into shade mid-afternoon. Approach is serious.',
    sunOnWall: 'Morning until mid-afternoon',
    bestIn: 'cool',
  },
  {
    id: 'gramps-westflank',
    parentId: 'gramps-main',
    name: 'West Flank',
    area: 'Grampians (Northern)',
    lat: -36.8934,
    lon: 142.3754,
    elevation: 270,
    aspect: 'W',
    rockType: 'sandstone',
    dryRating: 5,
    idealTemp: [10, 22],
    shade: 'morning',
    driveTime: '3h45',
    trip: 'both',
    notes: 'West-facing sport cliff with a roof providing morning shade. Popular for hot summer mornings. Variety of grades, mostly bolted. Below Taipan Wall.',
    sunOnWall: 'Afternoon only (shade until early/mid afternoon)',
    bestIn: 'warm',
  },
  {
    id: 'gramps-iforget',
    parentId: 'gramps-main',
    name: 'I Forget Walls',
    area: 'Grampians (Northern)',
    lat: -36.8945,
    lon: 142.3845,
    elevation: 280,
    aspect: 'SE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Popular moderate sport crag, 30-min walk from Stapylton Campground. SE-facing — morning sun, gets too hot by 2pm in late October. Bring helmet — some loose rock and lines still being cleaned.',
    sunOnWall: 'Morning only (hot by 2pm in summer)',
    bestIn: 'mild',
  },
  {
    id: 'gramps-ravine',
    parentId: 'gramps-main',
    name: 'The Ravine',
    area: 'Grampians (Northern)',
    lat: -36.9020,
    lon: 142.4080,
    elevation: 350,
    aspect: 'S',
    rockType: 'sandstone',
    dryRating: 3,
    idealTemp: [12, 24],
    shade: 'all-day',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Hidden canyon east of the olive plantation. South face is shady until 4pm — made for summer. North cave is steep sport. Lush valley, no winter sun, slow to dry. Mosquitoes — bring repellent.',
    sunOnWall: 'Shade until 4pm in summer; no sun in winter',
    bestIn: 'warm',
  },
  {
    id: 'gramps-vandiemens',
    parentId: 'gramps-main',
    name: "Van Diemen's Land",
    area: 'Grampians (Northern)',
    lat: -36.8936,
    lon: 142.3855,
    elevation: 320,
    aspect: 'E',
    rockType: 'sandstone',
    dryRating: 5,
    idealTemp: [6, 18],
    shade: 'afternoon',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Steep sport amphitheatre at Hollow Mountain — morning sun, afternoon shade. Several excellent grade 22–26s. Best after lunch in cooler weather.',
    sunOnWall: 'Morning only',
    bestIn: 'cool',
  },
  {
    id: 'gramps-dreamtime',
    parentId: 'gramps-main',
    name: 'Dreamtime Wall',
    area: 'Grampians (Northern)',
    lat: -36.8985,
    lon: 142.3920,
    elevation: 340,
    aspect: 'N',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [4, 16],
    shade: 'none',
    driveTime: '3h45',
    trip: 'both',
    notes: 'Striking steep wall east of Mt Stapylton — home of Dreamtime and several elite sport routes. North-facing — winter sun all day. Cultural-heritage closures may apply on some lines — check Parks Vic before climbing.',
    sunOnWall: 'Most of the day (north-facing, winter sun)',
    bestIn: 'cold',
  },
  {
    id: 'gramps-hallsgap',
    parentId: 'gramps-main',
    name: 'Halls Gap Area',
    area: 'Grampians (Central)',
    lat: -37.1372,
    lon: 142.5235,
    elevation: 280,
    aspect: 'SE',
    rockType: 'sandstone',
    dryRating: 4,
    idealTemp: [10, 24],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Scattered easy-access cliffs around Halls Gap valley — The Watchtower, Sundial, Punter’s Pinnacle. Slabby short routes plus bouldering at Venus Baths. SE/E-facing, mostly morning sun. Good rainy-day backup with quick approaches.',
    sunOnWall: 'Morning only',
    bestIn: 'mild',
  },

  // — Mt Buffalo —
  {
    id: 'buffalo-main',
    name: 'Mt Buffalo',
    area: 'Mt Buffalo',
    lat: -36.7367,
    lon: 146.8153,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [10, 24],
    shade: 'mixed',
    driveTime: '4h',
    trip: 'both',
    notes: 'High-altitude granite plateau (1500m+). Cooler than the plains — summer refuge. Watch weather closely: storms move fast above the treeline. Multi-pitch trad on The Cathedral, sport at Eurobin Falls.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-cathedral',
    parentId: 'buffalo-main',
    name: 'The Cathedral',
    area: 'Mt Buffalo',
    lat: -36.7367,
    lon: 146.8153,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Iconic alpine granite tor on the Buffalo plateau. Mostly trad with the odd sport route. Best in summer — high elevation means cold, snow possible Apr–Oct. Approach via Cathedral–Hump track. Long days.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-hump',
    parentId: 'buffalo-main',
    name: 'The Hump Area',
    area: 'Mt Buffalo',
    lat: -36.7383,
    lon: 146.8158,
    elevation: 1695,
    aspect: 'NE',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 24],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Highest point on the plateau \u2014 long granite walls, mixed sport and trad. Can be windy and exposed. Summer-only realistically. Spectacular position.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-eurobin',
    parentId: 'buffalo-main',
    name: 'Eurobin Falls',
    area: 'Mt Buffalo',
    lat: -36.7611,
    lon: 146.8261,
    elevation: 480,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 2,
    idealTemp: [12, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Polished water-washed granite slabs at the base of the mountain \u2014 several degrees warmer than the plateau. Sun nearly all morning. Slow to dry, best left for drier seasons. Swimming holes at the base. Long easy slabs (grades 14\u201324).',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-mackeys',
    parentId: 'buffalo-main',
    name: 'Mackeys Lookout',
    area: 'Mt Buffalo',
    lat: -36.7250,
    lon: 146.7950,
    elevation: 1400,
    aspect: 'NW',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Big multi-pitch trad and sport on the western edge of the plateau. NW aspect catches afternoon sun. Up to 240m walls. Long days, committing approaches.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-mcleod',
    parentId: 'buffalo-main',
    name: 'Mt McLeod',
    area: 'Mt Buffalo',
    lat: -36.6944,
    lon: 146.8367,
    elevation: 1600,
    aspect: 'S',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [14, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Remote northern end of the plateau \u2014 several km walk-in via Rocky Creek. Free remote camping. South-facing, shady, stays cool. Up to 160m walls. For when you want solitude.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-gorge-south',
    parentId: 'buffalo-main',
    name: 'The Gorge \u2013 South Side',
    area: 'Mt Buffalo',
    lat: -36.7414,
    lon: 146.8089,
    elevation: 1300,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '4h',
    trip: 'both',
    notes: 'Sunny north-facing side of the gorge \u2014 224 routes including \u201cWhere Angels Fear To Tread\u201d (263m grade 17). Hang-glider lookout access, abseil approaches common. Sun all day, can bake in summer.',
    bestIn: 'cool',
  },
  {
    id: 'buffalo-gorge-north',
    parentId: 'buffalo-main',
    name: 'The Gorge \u2013 North Side',
    area: 'Mt Buffalo',
    lat: -36.7367,
    lon: 146.8083,
    elevation: 1300,
    aspect: 'S',
    rockType: 'granite',
    dryRating: 3,
    idealTemp: [14, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'The famous North Wall \u2014 home to Ozymandias (280m) and Australia\u2019s biggest aid lines. Shady, cold, holds moisture. Some winter aid climbing possible. Up to 110m. Adventure terrain.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-reservoir',
    parentId: 'buffalo-main',
    name: 'Reservoir Environs',
    area: 'Mt Buffalo',
    lat: -36.7444,
    lon: 146.8125,
    elevation: 1320,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 24],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Short single-pitch trad and slabs near the reservoir. Easy access. East-facing \u2014 sunny mornings, shady afternoons. Up to 22m. Good warm-up venue.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-catani',
    parentId: 'buffalo-main',
    name: 'Lake Catani',
    area: 'Mt Buffalo',
    lat: -36.7456,
    lon: 146.8086,
    elevation: 1310,
    aspect: 'NE',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Catani slabs \u2014 beginner-friendly short routes near the campground. 82 routes up to 24m. Easy walk-in from the campsite. Good for warm-ups and rest days.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-lesouef',
    parentId: 'buffalo-main',
    name: 'Le Souef Plateau',
    area: 'Mt Buffalo',
    lat: -36.7300,
    lon: 146.8200,
    elevation: 1500,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 22],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Plateau crag with mixed trad and sport, 53 routes up to 22m. West-facing afternoon sun. Quieter alternative to the popular trade crags.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-buckland',
    parentId: 'buffalo-main',
    name: 'Buckland Slabs',
    area: 'Mt Buffalo',
    lat: -36.7800,
    lon: 146.7700,
    elevation: 600,
    aspect: 'N',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [10, 22],
    shade: 'none',
    driveTime: '4h',
    trip: 'both',
    notes: 'Lower-elevation granite slabs in the Buckland Valley below the plateau. North-facing \u2014 sun all day, warmer than the plateau. Dries fast. Up to 57m. Useful when the top is socked-in.',
    bestIn: 'cool',
  },
  {
    id: 'buffalo-tatra',
    parentId: 'buffalo-main',
    name: 'Tatra Inn',
    area: 'Mt Buffalo',
    lat: -36.7350,
    lon: 146.8050,
    elevation: 1450,
    aspect: 'E',
    rockType: 'granite',
    dryRating: 4,
    idealTemp: [12, 22],
    shade: 'afternoon',
    driveTime: '4h',
    trip: 'both',
    notes: 'Easy-access plateau crag near the old Tatra Inn site. 30 routes up to 24m. East-facing \u2014 morning sun, cooler afternoons. Mixed trad and sport.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-backwall',
    parentId: 'buffalo-main',
    name: 'The Back Wall Area',
    area: 'Mt Buffalo',
    lat: -36.7320,
    lon: 146.8170,
    elevation: 1500,
    aspect: 'S',
    rockType: 'granite',
    dryRating: 3,
    idealTemp: [14, 26],
    shade: 'all-day',
    driveTime: '4h',
    trip: 'both',
    notes: 'Big shady south-facing wall with trad and aid lines up to 110m. Cool, holds moisture. For long days when the sunny crags are too hot.',
    bestIn: 'warm',
  },
  {
    id: 'buffalo-horn',
    parentId: 'buffalo-main',
    name: 'The Horn Area',
    area: 'Mt Buffalo',
    lat: -36.7458,
    lon: 146.8378,
    elevation: 1723,
    aspect: 'W',
    rockType: 'granite',
    dryRating: 5,
    idealTemp: [12, 24],
    shade: 'morning',
    driveTime: '4h',
    trip: 'both',
    notes: 'Sharp granite at the road\u2019s end \u2014 the Horn summit (1723m, highest on the plateau). 113 routes, mostly short trad and sport with bolts. Classic intro: Peroxide Blonde (gr 20 ar\u00eate). Wind-blasted, dries fast. West-facing afternoon sun.',
    bestIn: 'warm',
  },
];

// Group crags by parent area for the UI summary
export const AREAS = {
  'Mt Macedon': ['camels-hump'],
  'Werribee Gorge': ['falcons-lookout'],
  'Cathedral Ranges': ['cathedral-balcony'],
  'You Yangs': ['youyangs-main', 'youyangs-flatrock', 'youyangs-gravelpit', 'youyangs-royaltywalls', 'youyangs-adamblock'],
  'Clunes': ['mt-beckworth'],
  'Brisbane Ranges': ['staughton-vale'],
  'Harcourt': ['mt-alexander', 'harcourt-dogrocks', 'harcourt-wabbitwocks', 'harcourt-scorpionrocks'],
  'Mt Arapiles': ['arap-main', 'arap-central', 'arap-cgleft', 'arap-cgright', 'arap-bard', 'arap-fang', 'arap-organpipes', 'arap-atridae', 'arap-watchtower', 'arap-kingrat', 'arap-piloterror', 'arap-tigerwall', 'arap-pharos', 'arap-bluffs', 'arap-mitre', 'arap-northern'],
  'Grampians': ['gramps-main', 'gramps-stapylton', 'gramps-taipan', 'gramps-dreamtime', 'gramps-bundaleer', 'gramps-muline', 'gramps-vicrange', 'gramps-guardhouse', 'gramps-rosea', 'gramps-westflank', 'gramps-iforget', 'gramps-ravine', 'gramps-vandiemens', 'gramps-hallsgap'],
  'Mt Buffalo': ['buffalo-main', 'buffalo-cathedral', 'buffalo-hump', 'buffalo-eurobin', 'buffalo-mackeys', 'buffalo-mcleod', 'buffalo-gorge-south', 'buffalo-gorge-north', 'buffalo-reservoir', 'buffalo-catani', 'buffalo-lesouef', 'buffalo-buckland', 'buffalo-tatra', 'buffalo-backwall', 'buffalo-horn'],
};
